Updating website with tentative agenda
open-source-eda-birds-of-a-feather/open-source-eda-birds-of-a-feather.github.io pull request #1
Opened 2023-07-05 23:36 UTC by QuantamHD

2023-07-05 23:50 UTC, tspyrou approved these changes

2023-07-06 00:00 UTC, tspyrou requested changes

2023-07-06 00:00 UTC, tspyrou commented on README.md
> +  - "State and Directions for OS EDA + OpenROAD initiative transition from DARPA with latchup parts"
Per Andrew remove latchup parts

2023-07-06 02:11 UTC, dralabeing commented
Please add Umar Shah as the additional speaker along with Karan Singh for AWS.

Also, Missing Sameer Shende- Speaker under " Updates and New Directions in Open Source:
Title: E4S Extreme Scientific Software Stack for Open EDA flows and Performance (this will be specified accurately by him- I am just mentioning the topic  gist)

2023-07-06 14:49 UTC, tspyrou approved these changes

2023-07-06 15:07 UTC, merged